// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserSupportSystem.Data.DB;

#nullable disable

namespace UserSupportSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230815192633_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserSupportSystem.Data.DTO.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AgentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentTypeId");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("UserSupportSystem.Data.DTO.AgentRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActiveCount")
                        .HasColumnType("int");

                    b.Property<int>("AgentType")
                        .HasColumnType("int");

                    b.Property<int>("MaxHandleCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("UserSupportSystem.Data.DTO.Agent", b =>
                {
                    b.HasOne("UserSupportSystem.Data.DTO.AgentRole", "AgentType")
                        .WithMany()
                        .HasForeignKey("AgentTypeId");

                    b.Navigation("AgentType");
                });
#pragma warning restore 612, 618
        }
    }
}
